import React, { useState } from "react";
import { Form } from "react-bootstrap";
import axios from "axios";

function New() {
  const [recipeData, setRecipeData] = useState({
    id: Date.now(), // generated by database
    user_id: localStorage.getItem("token"), // automatically grabbed from authorization token
    title: "", // string, required
    source: "", // string, optional
    ingredients: "", // text, required
    instructions: "", // text, required
    notes: "", // text, optional
    categories: [], // array of category ids*, optional
  });
  const handleChange = (e) => {
    setRecipeData({
      ...recipeData,
      [e.target.name]: e.target.value,
    });
  };
  return (
    <div>
      <h1>This is my New page</h1>
      <Form>
        <Form.Group className="form-group">
          <Form.Label>Recipe Name: </Form.Label>
          <Form.Control
            name="title"
            value={recipeData.title}
            onChange={handleChange}
            type="Recipe Name"
            placeholder="Recipe Name"
          />
          <Form.Text className="text-muted"></Form.Text>
        </Form.Group>

        <Form.Group className="form-group">
          <Form.Label>Recipe Source: </Form.Label>
          <Form.Control
            name="source"
            value={recipeData.source}
            onChange={handleChange}
            type="name"
            placeholder="Source"
          />
          <Form.Text className="text-muted"></Form.Text>
        </Form.Group>

        <Form.Group className="form-group">
          <label htmlFor="exampleFormControlTextarea1">Ingredients: </label>
          <textarea
            name="ingredients"
            value={recipeData.ingredients}
            onChange={handleChange}
            className="form-control"
            name="ingredients"
            id="exampleFormControlTextarea1"
            rows="5"
          />
        </Form.Group>

        <Form.Group className="form-group">
          <label htmlFor="exampleFormControlTextarea1">Instructions: </label>
          <textarea
            className="form-control"
            name="instructions"
            value={recipeData.instructions}
            onChange={handleChange}
            id="exampleFormControlTextarea1"
            rows="5"
          />
        </Form.Group>
        <Form.Group className="form-group">
          <label htmlFor="exampleFormControlTextarea1">Notes: </label>
          <textarea
            className="form-control"
            name="notes"
            value={recipeData.notes}
            onChange={handleChange}
            id="exampleFormControlTextarea1"
            rows="5"
          />
        </Form.Group>

        <div class="dropdown">
          <button
            class="btn btn-secondary dropdown-toggle"
            type="button"
            id="dropdownMenuButton"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Categories
          </button>
          <div
            class="dropdown-menu"
            name="category"
            aria-labelledby="dropdownMenuButton"
          >
            <p class="dropdown-item" value={1}>
              Breakfast
            </p>
            <p class="dropdown-item" value={2}>
              Lunch
            </p>
            <p class="dropdown-item" value={3}>
              Dinner
            </p>
            <p class="dropdown-item" value={4}>
              Dessert
            </p>
          </div>
        </div>
      </Form>
      <div>
        <button class="btn btn-success" type="submit">
          Submit Recipe
        </button>
      </div>
    </div>
  );
}

export default New;
